namespace CommanderLayer.Core.Model
{
    /// <summary>Coarse engine class of a unit.</summary>
    public enum UnitClass
    {
        Other,
        Aircraft,
        Ship,
        GroundVehicle,
        Missile,
        Building,
        Infantry
    }

    /// <summary>Tactical role, refined from class + subtype + weapon capability.</summary>
    public enum Role
    {
        Unknown,
        // air
        Fighter, StrikeAircraft, Bomber, Sead, AwacsEw, TransportAir,
        // ground
        Armor, Ifv, Apc, Artillery, GroundAirDefense, GroundRadar, Supply, Ugv,
        // ship
        Carrier, AirDefenseShip, CombatShip, TransportShip,
        // other
        CruiseMissile, BuildingMilitary, Infantry, Other
    }

    /// <summary>
    /// Unity-free primitives extracted from a unit/definition by the Game layer, fed to RoleClassifier.
    /// Subtypes are the game's OWN enums (mirrored into Core.Generated by the code generator), so
    /// classification is type-safe and keyed off the single source of truth — no magic strings.
    /// Exactly one of Vehicle/Ship/Building is set, matching Class (null otherwise).
    /// </summary>
    public sealed class UnitDescriptor
    {
        public UnitClass Class { get; }
        public Generated.VehicleType? Vehicle { get; }
        public Generated.ShipType? Ship { get; }
        public Generated.BuildingType? Building { get; }
        // RoleIdentity (what it can DO)
        public float AntiSurface { get; }
        public float AntiAir { get; }
        public float AntiRadar { get; }
        public float AntiMissile { get; }
        public bool HasRadar { get; }
        public bool HasTroops { get; }
        public bool HasCargo { get; }
        public float CaptureStrength { get; }
        public int ArmorTier { get; }
        public bool Commandable { get; }

        public UnitDescriptor(
            UnitClass cls,
            float antiSurface, float antiAir, float antiRadar, float antiMissile,
            bool hasRadar, bool hasTroops, bool hasCargo,
            float captureStrength, int armorTier, bool commandable,
            Generated.VehicleType? vehicle = null,
            Generated.ShipType? ship = null,
            Generated.BuildingType? building = null)
        {
            Class = cls;
            Vehicle = vehicle;
            Ship = ship;
            Building = building;
            AntiSurface = antiSurface;
            AntiAir = antiAir;
            AntiRadar = antiRadar;
            AntiMissile = antiMissile;
            HasRadar = hasRadar;
            HasTroops = hasTroops;
            HasCargo = hasCargo;
            CaptureStrength = captureStrength;
            ArmorTier = armorTier;
            Commandable = commandable;
        }
    }

    /// <summary>Classification result: role + the capability flags the planner selects on.</summary>
    public readonly struct UnitCapability
    {
        public readonly Role Role;
        public readonly bool CanEngageGround;
        public readonly bool CanEngageAir;
        public readonly bool CanCapture;
        public readonly bool IsSupply;
        public readonly bool IsAirDefense;

        public UnitCapability(Role role, bool canEngageGround, bool canEngageAir, bool canCapture,
            bool isSupply, bool isAirDefense)
        {
            Role = role;
            CanEngageGround = canEngageGround;
            CanEngageAir = canEngageAir;
            CanCapture = canCapture;
            IsSupply = isSupply;
            IsAirDefense = isAirDefense;
        }
    }
}
