// <auto-generated> by tools/CommanderLayer.CodeGen. DO NOT EDIT.
//   One test asserting every manifest member still exists with the expected shape.
#pragma warning disable CS1591

using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace CommanderLayer.GameContract.Tests
{
    public class GeneratedManifestTests
    {
        [Fact]
        public void Manifest_members_all_exist_with_expected_shape()
        {
            if (!Game.Available) return;
            var fail = new List<string>();
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "leftButtons")) fail.Add("VirtualMFD.leftButtons (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "rightButtons")) fail.Add("VirtualMFD.rightButtons (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "leftScreens")) fail.Add("VirtualMFD.leftScreens (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "rightScreens")) fail.Add("VirtualMFD.rightScreens (field)");
            if (!Game.Type("DynamicMap").Fields.Any(x => x.Name == "mapDisplayFactor" && x.IsPublic)) fail.Add("DynamicMap.mapDisplayFactor (field,public)");
            if (!Game.Type("DynamicMap").Fields.Any(x => x.Name == "iconLayer" && x.IsPublic)) fail.Add("DynamicMap.iconLayer (field,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "TryGetCursorCoordinates" && x.IsPublic)) fail.Add("DynamicMap.TryGetCursorCoordinates (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Maximize" && x.IsPublic)) fail.Add("DynamicMap.Maximize (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Minimize" && x.IsPublic)) fail.Add("DynamicMap.Minimize (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Update")) fail.Add("DynamicMap.Update (method)");
            if (!Game.Type("DynamicMap").Properties.Any(x => x.Name == "mapMaximized" && x.GetMethod != null && x.GetMethod.IsPublic && x.GetMethod != null && x.GetMethod.IsStatic)) fail.Add("DynamicMap.mapMaximized (property,public,static)");
            if (!Game.Type("UnitRegistry").Fields.Any(x => x.Name == "allUnits" && x.IsPublic)) fail.Add("UnitRegistry.allUnits (field,public)");
            if (!Game.Type("Unit").Properties.Any(x => x.Name == "NetworkHQ")) fail.Add("Unit.NetworkHQ (property)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "disabled" && x.IsPublic)) fail.Add("Unit.disabled (field,public)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "unitName" && x.IsPublic)) fail.Add("Unit.unitName (field,public)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "definition" && x.IsPublic)) fail.Add("Unit.definition (field,public)");
            if (!Game.Type("Unit").Properties.Any(x => x.Name == "CaptureStrength")) fail.Add("Unit.CaptureStrength (property)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "persistentID")) fail.Add("Unit.persistentID (field)");
            if (!Game.Type("ICommandable").Properties.Any(x => x.Name == "UnitCommand")) fail.Add("ICommandable.UnitCommand (property)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalHQ" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalHQ (method,public,static)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalFaction" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalFaction (method,public,static)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalPlayer" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalPlayer (method,public,static)");
            if (!Game.Type("Faction").Fields.Any(x => x.Name == "factionName" && x.IsPublic)) fail.Add("Faction.factionName (field,public)");
            if (!Game.Type("Faction").Fields.Any(x => x.Name == "color" && x.IsPublic)) fail.Add("Faction.color (field,public)");
            if (!Game.Type("UnitCommand").Methods.Any(x => x.Name == "SetDestination" && x.IsPublic)) fail.Add("UnitCommand.SetDestination (method,public)");
            if (!Game.Type("Ship").Methods.Any(x => x.Name == "SetHoldPosition" && x.IsPublic)) fail.Add("Ship.SetHoldPosition (method,public)");
            if (!Game.Type("GroundVehicle").Methods.Any(x => x.Name == "SetHoldPosition" && x.IsPublic)) fail.Add("GroundVehicle.SetHoldPosition (method,public)");
            if (!Game.Type("GlobalPosition").Methods.Any(x => x.Name == "AsVector3")) fail.Add("GlobalPosition.AsVector3 (method)");
            if (!Game.Type("NuclearOption.Networking.Player").Methods.Any(x => x.Name == "CmdPurchaseConvoy")) fail.Add("NuclearOption.Networking.Player.CmdPurchaseConvoy (method)");
            if (!Game.Type("Faction").Methods.Any(x => x.Name == "GetConvoyGroups")) fail.Add("Faction.GetConvoyGroups (method)");
            if (!Game.Type("Faction/ConvoyGroup").Methods.Any(x => x.Name == "GetCost")) fail.Add("Faction/ConvoyGroup.GetCost (method)");
            if (!Game.Type("Faction/ConvoyGroup").Fields.Any(x => x.Name == "Name")) fail.Add("Faction/ConvoyGroup.Name (field)");
            if (!Game.Type("FactionHQ").Properties.Any(x => x.Name == "factionFunds" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("FactionHQ.factionFunds (property,public)");
            if (Game.Module.GetType("IRearmable") == null && Game.Module.GetTypes().All(t => t.Name != "IRearmable")) fail.Add("IRearmable (type)");
            if (!Game.Type("Airbase").Properties.Any(x => x.Name == "CurrentHQ")) fail.Add("Airbase.CurrentHQ (property)");
            if (!Game.Type("Airbase").Fields.Any(x => x.Name == "center")) fail.Add("Airbase.center (field)");
            if (!Game.Type("AIPilotCombatModes").Methods.Any(x => x.Name == "AssessHQTargets")) fail.Add("AIPilotCombatModes.AssessHQTargets (method)");
            if (!Game.Type("CombatAI").Methods.Any(x => x.Name == "ChooseHQTarget" && x.IsStatic)) fail.Add("CombatAI.ChooseHQTarget (method,static)");
            if (!Game.Type("GameAssets").Properties.Any(x => x.Name == "i" && x.GetMethod != null && x.GetMethod.IsStatic)) fail.Add("GameAssets.i (property,static)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDFriendly" && x.IsPublic)) fail.Add("GameAssets.HUDFriendly (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDHostile" && x.IsPublic)) fail.Add("GameAssets.HUDHostile (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDNeutral" && x.IsPublic)) fail.Add("GameAssets.HUDNeutral (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "playerNameFont" && x.IsPublic)) fail.Add("GameAssets.playerNameFont (field,public)");
            if (!Game.Type("MapToolTip").Fields.Any(x => x.Name == "circle1")) fail.Add("MapToolTip.circle1 (field)");
            if (!Game.Type("MapToolTip").Fields.Any(x => x.Name == "circle2")) fail.Add("MapToolTip.circle2 (field)");
            if (!Game.Type("MapToolTip").Fields.Any(x => x.Name == "line1")) fail.Add("MapToolTip.line1 (field)");
            if (!Game.Type("FactionHQ").Fields.Any(x => x.Name == "trackingDatabase" && x.IsPublic)) fail.Add("FactionHQ.trackingDatabase (field,public)");
            if (!Game.Type("FactionHQ").Methods.Any(x => x.Name == "GetTargetsWithinRange" && x.IsPublic)) fail.Add("FactionHQ.GetTargetsWithinRange (method,public)");
            if (!Game.Type("FactionHQ").Methods.Any(x => x.Name == "GetNearestGroundEnemy" && x.IsPublic)) fail.Add("FactionHQ.GetNearestGroundEnemy (method,public)");
            if (!Game.Type("FactionHQ").Methods.Any(x => x.Name == "GetAircraftThreat" && x.IsPublic)) fail.Add("FactionHQ.GetAircraftThreat (method,public)");
            if (!Game.Type("RoleIdentity").Methods.Any(x => x.Name == "OpportunityAgainst")) fail.Add("RoleIdentity.OpportunityAgainst (method)");
            if (!Game.Type("RoleIdentity").Fields.Any(x => x.Name == "antiSurface" && x.IsPublic)) fail.Add("RoleIdentity.antiSurface (field,public)");
            if (!Game.Type("RoleIdentity").Fields.Any(x => x.Name == "antiAir" && x.IsPublic)) fail.Add("RoleIdentity.antiAir (field,public)");
            Assert.True(fail.Count == 0, "Manifest drift vs Assembly-CSharp — run scripts/generate-types.sh:\n  - " + string.Join("\n  - ", fail));
        }
    }
}
