// <auto-generated> by tools/CommanderLayer.CodeGen. DO NOT EDIT.
//   One test asserting every manifest member still exists with the expected shape.
#pragma warning disable CS1591

using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace CommanderLayer.GameContract.Tests
{
    public class GeneratedManifestTests
    {
        [Fact]
        public void Manifest_members_all_exist_with_expected_shape()
        {
            if (!Game.Available) return;
            var fail = new List<string>();
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "leftButtons")) fail.Add("VirtualMFD.leftButtons (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "rightButtons")) fail.Add("VirtualMFD.rightButtons (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "leftScreens")) fail.Add("VirtualMFD.leftScreens (field)");
            if (!Game.Type("VirtualMFD").Fields.Any(x => x.Name == "rightScreens")) fail.Add("VirtualMFD.rightScreens (field)");
            if (!Game.Type("DynamicMap").Fields.Any(x => x.Name == "mapDisplayFactor" && x.IsPublic)) fail.Add("DynamicMap.mapDisplayFactor (field,public)");
            if (!Game.Type("DynamicMap").Fields.Any(x => x.Name == "iconLayer" && x.IsPublic)) fail.Add("DynamicMap.iconLayer (field,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "TryGetCursorCoordinates" && x.IsPublic)) fail.Add("DynamicMap.TryGetCursorCoordinates (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Maximize" && x.IsPublic)) fail.Add("DynamicMap.Maximize (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Minimize" && x.IsPublic)) fail.Add("DynamicMap.Minimize (method,public)");
            if (!Game.Type("DynamicMap").Methods.Any(x => x.Name == "Update")) fail.Add("DynamicMap.Update (method)");
            if (!Game.Type("DynamicMap").Properties.Any(x => x.Name == "mapMaximized" && x.GetMethod != null && x.GetMethod.IsPublic && x.GetMethod != null && x.GetMethod.IsStatic)) fail.Add("DynamicMap.mapMaximized (property,public,static)");
            if (!Game.Type("UnitRegistry").Fields.Any(x => x.Name == "allUnits" && x.IsPublic)) fail.Add("UnitRegistry.allUnits (field,public)");
            if (!Game.Type("Unit").Properties.Any(x => x.Name == "NetworkHQ")) fail.Add("Unit.NetworkHQ (property)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "disabled" && x.IsPublic)) fail.Add("Unit.disabled (field,public)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "unitName" && x.IsPublic)) fail.Add("Unit.unitName (field,public)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "definition" && x.IsPublic)) fail.Add("Unit.definition (field,public)");
            if (!Game.Type("Unit").Properties.Any(x => x.Name == "CaptureStrength")) fail.Add("Unit.CaptureStrength (property)");
            if (!Game.Type("Unit").Fields.Any(x => x.Name == "persistentID")) fail.Add("Unit.persistentID (field)");
            if (!Game.Type("ICommandable").Properties.Any(x => x.Name == "UnitCommand")) fail.Add("ICommandable.UnitCommand (property)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalHQ" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalHQ (method,public,static)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalFaction" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalFaction (method,public,static)");
            if (!Game.Type("GameManager").Methods.Any(x => x.Name == "GetLocalPlayer" && x.IsPublic && x.IsStatic)) fail.Add("GameManager.GetLocalPlayer (method,public,static)");
            if (!Game.Type("Faction").Fields.Any(x => x.Name == "factionName" && x.IsPublic)) fail.Add("Faction.factionName (field,public)");
            if (!Game.Type("Faction").Fields.Any(x => x.Name == "color" && x.IsPublic)) fail.Add("Faction.color (field,public)");
            if (!Game.Type("UnitCommand").Methods.Any(x => x.Name == "SetDestination" && x.IsPublic)) fail.Add("UnitCommand.SetDestination (method,public)");
            if (!Game.Type("Ship").Methods.Any(x => x.Name == "SetHoldPosition" && x.IsPublic)) fail.Add("Ship.SetHoldPosition (method,public)");
            if (!Game.Type("GroundVehicle").Methods.Any(x => x.Name == "SetHoldPosition" && x.IsPublic)) fail.Add("GroundVehicle.SetHoldPosition (method,public)");
            if (!Game.Type("GlobalPosition").Methods.Any(x => x.Name == "AsVector3")) fail.Add("GlobalPosition.AsVector3 (method)");
            if (!Game.Type("NuclearOption.Networking.Player").Methods.Any(x => x.Name == "CmdPurchaseConvoy")) fail.Add("NuclearOption.Networking.Player.CmdPurchaseConvoy (method)");
            if (!Game.Type("Faction").Methods.Any(x => x.Name == "GetConvoyGroups")) fail.Add("Faction.GetConvoyGroups (method)");
            if (!Game.Type("Faction/ConvoyGroup").Methods.Any(x => x.Name == "GetCost")) fail.Add("Faction/ConvoyGroup.GetCost (method)");
            if (!Game.Type("Faction/ConvoyGroup").Fields.Any(x => x.Name == "Name")) fail.Add("Faction/ConvoyGroup.Name (field)");
            if (!Game.Type("FactionHQ").Properties.Any(x => x.Name == "factionFunds" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("FactionHQ.factionFunds (property,public)");
            if (Game.Module.GetType("IRearmable") == null && Game.Module.GetTypes().All(t => t.Name != "IRearmable")) fail.Add("IRearmable (type)");
            if (!Game.Type("Airbase").Properties.Any(x => x.Name == "CurrentHQ")) fail.Add("Airbase.CurrentHQ (property)");
            if (!Game.Type("Airbase").Fields.Any(x => x.Name == "center")) fail.Add("Airbase.center (field)");
            if (!Game.Type("AIPilotCombatModes").Methods.Any(x => x.Name == "NoTarget")) fail.Add("AIPilotCombatModes.NoTarget (method)");
            if (!Game.Type("PilotBaseState").Fields.Any(x => x.Name == "aircraft")) fail.Add("PilotBaseState.aircraft (field)");
            if (!Game.Type("PilotBaseState").Fields.Any(x => x.Name == "destination")) fail.Add("PilotBaseState.destination (field)");
            if (!Game.Type("GameAssets").Properties.Any(x => x.Name == "i" && x.GetMethod != null && x.GetMethod.IsStatic)) fail.Add("GameAssets.i (property,static)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "playerNameFont" && x.IsPublic)) fail.Add("GameAssets.playerNameFont (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDFriendly" && x.IsPublic)) fail.Add("GameAssets.HUDFriendly (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDHostile" && x.IsPublic)) fail.Add("GameAssets.HUDHostile (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDNeutral" && x.IsPublic)) fail.Add("GameAssets.HUDNeutral (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDFriendlySelected" && x.IsPublic)) fail.Add("GameAssets.HUDFriendlySelected (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDHostileSelected" && x.IsPublic)) fail.Add("GameAssets.HUDHostileSelected (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "HUDAirbaseNotAvailable" && x.IsPublic)) fail.Add("GameAssets.HUDAirbaseNotAvailable (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "airbaseSprite" && x.IsPublic)) fail.Add("GameAssets.airbaseSprite (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "targetUnitSprite" && x.IsPublic)) fail.Add("GameAssets.targetUnitSprite (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "targetUnitSpriteFriendly" && x.IsPublic)) fail.Add("GameAssets.targetUnitSpriteFriendly (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "missileWarningSprite" && x.IsPublic)) fail.Add("GameAssets.missileWarningSprite (field,public)");
            if (!Game.Type("GameAssets").Fields.Any(x => x.Name == "warheadSprite" && x.IsPublic)) fail.Add("GameAssets.warheadSprite (field,public)");
            if (!Game.Type("NuclearOption.UI.BetterBorder").Properties.Any(x => x.Name == "BorderThickness" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("NuclearOption.UI.BetterBorder.BorderThickness (property,public)");
            if (!Game.Type("NuclearOption.UI.BetterBorder").Properties.Any(x => x.Name == "FillColor" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("NuclearOption.UI.BetterBorder.FillColor (property,public)");
            if (!Game.Type("NuclearOption.UI.BetterBorder").Properties.Any(x => x.Name == "color" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("NuclearOption.UI.BetterBorder.color (property,public)");
            if (!Game.Type("NuclearOption.UI.BaseToggle").Properties.Any(x => x.Name == "isOn" && x.GetMethod != null && x.GetMethod.IsPublic)) fail.Add("NuclearOption.UI.BaseToggle.isOn (property,public)");
            if (!Game.Type("NuclearOption.UI.BaseToggle").Fields.Any(x => x.Name == "onValueChanged" && x.IsPublic)) fail.Add("NuclearOption.UI.BaseToggle.onValueChanged (field,public)");
            if (!Game.Type("NuclearOption.UI.BaseToggle").Methods.Any(x => x.Name == "SetIsOnWithoutNotify" && x.IsPublic)) fail.Add("NuclearOption.UI.BaseToggle.SetIsOnWithoutNotify (method,public)");
            if (Game.Module.GetType("NuclearOption.UI.BoxToggle") == null && Game.Module.GetTypes().All(t => t.Name != "NuclearOption.UI.BoxToggle")) fail.Add("NuclearOption.UI.BoxToggle (type)");
            if (Game.Module.GetType("NuclearOption.UI.SliderToggle") == null && Game.Module.GetTypes().All(t => t.Name != "NuclearOption.UI.SliderToggle")) fail.Add("NuclearOption.UI.SliderToggle (type)");
            if (!Game.Type("NuclearOption.UI.BetterToggleGroup").Methods.Any(x => x.Name == "SetIndex" && x.IsPublic)) fail.Add("NuclearOption.UI.BetterToggleGroup.SetIndex (method,public)");
            if (!Game.Type("NuclearOption.UI.BetterToggleGroup").Methods.Any(x => x.Name == "GetIndex" && x.IsPublic)) fail.Add("NuclearOption.UI.BetterToggleGroup.GetIndex (method,public)");
            if (!Game.Type("NuclearOption.UI.BetterToggleGroup").Methods.Any(x => x.Name == "SetFlags" && x.IsPublic)) fail.Add("NuclearOption.UI.BetterToggleGroup.SetFlags (method,public)");
            if (!Game.Type("NuclearOption.UI.BetterToggleGroup").Methods.Any(x => x.Name == "GetFlags" && x.IsPublic)) fail.Add("NuclearOption.UI.BetterToggleGroup.GetFlags (method,public)");
            if (!Game.Type("FactionHQ").Fields.Any(x => x.Name == "trackingDatabase" && x.IsPublic)) fail.Add("FactionHQ.trackingDatabase (field,public)");
            if (!Game.Type("RoleIdentity").Fields.Any(x => x.Name == "antiSurface" && x.IsPublic)) fail.Add("RoleIdentity.antiSurface (field,public)");
            if (!Game.Type("RoleIdentity").Fields.Any(x => x.Name == "antiAir" && x.IsPublic)) fail.Add("RoleIdentity.antiAir (field,public)");
            Assert.True(fail.Count == 0, "Manifest drift vs Assembly-CSharp — run scripts/generate-types.sh:\n  - " + string.Join("\n  - ", fail));
        }
    }
}
