using CommanderLayer.Core.Model;
using Gen = CommanderLayer.Core.Generated; // alias: the plugin assembly also sees the game's global enums

namespace CommanderLayer.Core.Roles
{
    /// <summary>
    /// Maps a Unity-free UnitDescriptor to a tactical Role + capability flags. Keyed off the game's OWN
    /// enums (mirrored into Core.Generated by the code generator), so it is type-safe and DRY — a game enum
    /// change fails the generated-enum contract test, forcing a regenerate. Pure and unit-testable.
    /// </summary>
    public static class RoleClassifier
    {
        private const float Engage = 0.05f; // min RoleIdentity value to count as "can engage"

        public static UnitCapability Classify(UnitDescriptor d)
        {
            var role = DeriveRole(d);
            bool canGround = d.AntiSurface > Engage;
            bool canAir = d.AntiAir > Engage;
            bool isAirDefense = role == Role.GroundAirDefense || role == Role.AirDefenseShip
                                || (canAir && !canGround && (d.Class == UnitClass.GroundVehicle || d.Class == UnitClass.Ship));
            bool canCapture = d.CaptureStrength > 0f
                              && (d.Class == UnitClass.GroundVehicle || d.Class == UnitClass.Ship || d.Class == UnitClass.Aircraft)
                              && role != Role.Ugv;
            bool isSupply = role == Role.Supply;
            return new UnitCapability(role, canGround, canAir, canCapture, isSupply, isAirDefense);
        }

        private static Role DeriveRole(UnitDescriptor d)
        {
            switch (d.Class)
            {
                case UnitClass.GroundVehicle:
                    return d.Vehicle switch
                    {
                        Gen.VehicleType.MBT => Role.Armor,
                        Gen.VehicleType.AFV => Role.Ifv,
                        Gen.VehicleType.LCV => Role.Ifv,
                        Gen.VehicleType.ART => Role.Artillery,
                        Gen.VehicleType.AAA => Role.GroundAirDefense,
                        Gen.VehicleType.IR_SAM => Role.GroundAirDefense,
                        Gen.VehicleType.R_SAM => Role.GroundAirDefense,
                        Gen.VehicleType.RDR => Role.GroundRadar,
                        Gen.VehicleType.TRUCK => Role.Supply,
                        Gen.VehicleType.UGV => Role.Ugv,
                        _ => FallbackGround(d)
                    };

                case UnitClass.Ship:
                    return d.Ship switch
                    {
                        Gen.ShipType.CV => Role.Carrier,
                        Gen.ShipType.LHA => Role.Carrier,
                        Gen.ShipType.DDG => Role.AirDefenseShip,
                        Gen.ShipType.FFG => Role.AirDefenseShip,
                        Gen.ShipType.LFD => Role.TransportShip,
                        Gen.ShipType.LC => Role.TransportShip,
                        Gen.ShipType.FFL => Role.CombatShip,
                        _ => (d.AntiAir > Engage && d.AntiAir >= d.AntiSurface) ? Role.AirDefenseShip : Role.CombatShip
                    };

                case UnitClass.Aircraft:
                    if (d.AntiRadar > 0.2f) return Role.Sead;
                    if (d.HasTroops || d.HasCargo) return Role.TransportAir;
                    if (d.HasRadar && d.AntiSurface < Engage && d.AntiAir < Engage) return Role.AwacsEw;
                    if (d.AntiAir > d.AntiSurface) return Role.Fighter;
                    if (d.AntiSurface > Engage) return Role.StrikeAircraft;
                    return Role.Fighter;

                case UnitClass.Missile:
                    return Role.CruiseMissile;
                case UnitClass.Building:
                    return Role.BuildingMilitary;
                case UnitClass.Infantry:
                    return Role.Infantry;
                default:
                    return Role.Other;
            }
        }

        private static Role FallbackGround(UnitDescriptor d)
        {
            if (d.AntiAir > d.AntiSurface && d.AntiAir > Engage) return Role.GroundAirDefense;
            if (d.HasRadar && d.AntiSurface < Engage && d.AntiAir < Engage) return Role.GroundRadar;
            if (d.HasCargo && d.AntiSurface < Engage) return Role.Supply;
            return Role.Ifv;
        }
    }
}
