using System.Collections.Generic;
using System.Linq;
using Nucleus.Core.Model;

namespace Nucleus.Core.Command
{
    /// <summary>
    /// Flattened, render-ready view of one <see cref="Operation"/> (and its driving objective) for the UI.
    /// Carries everything an objective-management row OR a selectable map marker needs — id, kind, place,
    /// priority, phase, assigned squads — with no object graph to walk, so the UI layer stays logic-free.
    /// Pure value type.
    /// </summary>
    public readonly struct OperationView
    {
        public string Id { get; }
        /// <summary>The driving objective's id (what CreateObjective returned / Edit/Move/Remove address).</summary>
        public string ObjectiveId { get; }
        public ObjectiveKind Kind { get; }
        public CombatPhase Phase { get; }
        public OperationStatus Status { get; }
        public int SquadCount { get; }
        public AutonomyLevel Autonomy { get; }
        /// <summary>The objective's world position — for the selectable map marker and the editor.</summary>
        public Vec3 Position { get; }
        public float Priority { get; }
        /// <summary>True when the objective was dropped by the player (vs. auto-generated by the AI commander).</summary>
        public bool PlayerOwned { get; }
        /// <summary>Enemies counted at the objective when the operation opened — lets the map show how defended it is.</summary>
        public int ThreatCount { get; }
        /// <summary>Of those, how many are air defenses (SAM/AAA) — the "do I need SEAD" signal.</summary>
        public int ThreatAirDefense { get; }

        public OperationView(string id, ObjectiveKind kind, CombatPhase phase, OperationStatus status,
            int squadCount, AutonomyLevel autonomy, string objectiveId = null, Vec3 position = default,
            float priority = 1f, bool playerOwned = false, int threatCount = 0, int threatAirDefense = 0)
        {
            Id = id;
            Kind = kind;
            Phase = phase;
            Status = status;
            SquadCount = squadCount;
            Autonomy = autonomy;
            ObjectiveId = objectiveId ?? id;
            Position = position;
            Priority = priority;
            PlayerOwned = playerOwned;
            ThreatCount = threatCount;
            ThreatAirDefense = threatAirDefense;
        }
    }

    /// <summary>Flattened, render-ready view of one <see cref="Squad"/> for the UI. Pure value type.</summary>
    public readonly struct SquadView
    {
        public string Id { get; }
        public string Name { get; }
        public RoleFamily Family { get; }
        public int Strength { get; }
        public SquadStatus Status { get; }
        /// <summary>Convenience flag so the UI layer can red-flag a hurt squad without referencing the
        /// SquadStatus enum (which lives in Nucleus.Squads, outside the Ui lib's allowed dependency set).</summary>
        public bool Depleted => Status == SquadStatus.Depleted;
        public string AssignedOperationId { get; }
        public AutonomyLevel Autonomy { get; }
        /// <summary>What the squad is doing right now, e.g. "DestroyTarget — Strike" or "Reserve". For the UI.</summary>
        public string Activity { get; }
        /// <summary>The squad's member unit ids — so the map can track its units + draw lines to its objective.</summary>
        public IReadOnlyList<string> MemberUnitIds { get; }
        /// <summary>Human composition, e.g. "2× MBT, 1× IFV" — empty when no roster role map was supplied.</summary>
        public string Composition { get; }
        /// <summary>Target strength (TargetComposition total) for "have/need" readouts; 0 when unknown.</summary>
        public int TargetStrength { get; }

        public SquadView(string id, string name, RoleFamily family, int strength, SquadStatus status,
            string assignedOperationId, AutonomyLevel autonomy, string activity, IReadOnlyList<string> memberUnitIds = null,
            string composition = "", int targetStrength = 0)
        {
            Id = id;
            Name = name;
            Family = family;
            Strength = strength;
            Status = status;
            AssignedOperationId = assignedOperationId;
            Autonomy = autonomy;
            Activity = activity ?? "";
            MemberUnitIds = memberUnitIds ?? new List<string>();
            Composition = composition ?? "";
            TargetStrength = targetStrength;
        }
    }

    /// <summary>
    /// An immutable, render-ready snapshot of the whole HQ for the UI: operations, squads, production status
    /// lines, the recent battle feed and the commander's autonomy. One read of this is everything a panel
    /// draws — no game/state references leak into the view layer. Pure Core.
    /// </summary>
    public sealed class HqSnapshot
    {
        public IReadOnlyList<OperationView> Operations { get; }
        public IReadOnlyList<SquadView> Squads { get; }
        public IReadOnlyList<string> Production { get; }
        public IReadOnlyList<ReportEvent> Recent { get; }
        /// <summary>The two command toggles (mod is always on).</summary>
        public bool AiCreatesObjectives { get; }
        public bool AiAutoFill { get; }

        public HqSnapshot(IReadOnlyList<OperationView> operations, IReadOnlyList<SquadView> squads,
            IReadOnlyList<string> production, IReadOnlyList<ReportEvent> recent,
            bool aiCreatesObjectives, bool aiAutoFill)
        {
            Operations = operations;
            Squads = squads;
            Production = production;
            Recent = recent;
            AiCreatesObjectives = aiCreatesObjectives;
            AiAutoFill = aiAutoFill;
        }
    }

    /// <summary>
    /// Pure projection from live commander state to a flat <see cref="HqSnapshot"/> the UI can render without
    /// any logic of its own. Null-safe: a missing log or production queue maps to empty lists. The one place
    /// where "what the screen shows" is computed.
    /// </summary>
    public static class HqView
    {
        public static HqSnapshot Build(CommanderState state, BattleLog log, ProductionQueue production,
            int recentCount = 10, IReadOnlyDictionary<string, Role> unitRoles = null)
        {
            var operations = state.Operations
                .Select(op => new OperationView(
                    op.Id, op.Objective.Kind, op.CombatPhase, op.Status, op.SquadIds.Count, op.Autonomy,
                    op.Objective.Id, op.Objective.Position, op.Objective.Priority,
                    op.Objective.Source == ObjectiveSource.Player,
                    op.InitialThreat?.Count ?? 0, op.InitialThreat?.AirDefenseCount ?? 0))
                .ToList();

            // An objective the player just dropped has no Operation yet (one forms when a squad is assigned —
            // by the AI auto-fill, or by the human). Surface those as placeholder rows/markers so a dropped
            // objective is immediately visible, selectable, editable and movable — even with auto-fill OFF.
            var withOps = new System.Collections.Generic.HashSet<string>(
                state.Operations.Select(o => o.Objective.Id));
            foreach (var obj in state.Objectives)
            {
                if (withOps.Contains(obj.Id)) continue;
                operations.Add(new OperationView(
                    obj.Id, obj.Kind, CombatPhase.Recon, OperationStatus.Planning, 0, AutonomyLevel.Auto,
                    obj.Id, obj.Position, obj.Priority, obj.Source == ObjectiveSource.Player));
            }

            var squads = state.Squads.Squads
                .Select(s => new SquadView(
                    s.Id, s.Name, s.Family, s.Strength, s.Status, s.AssignedOperationId, s.Autonomy,
                    SquadActivity(s, state), new List<string>(s.MemberUnitIds),
                    CompositionLabel(s, unitRoles), s.TargetComposition?.Total ?? 0))
                .ToList();

            var productionLines = production != null
                ? production.Describe()
                : (IReadOnlyList<string>)new List<string>();

            var recent = log != null
                ? log.Recent(recentCount)
                : (IReadOnlyList<ReportEvent>)new List<ReportEvent>();

            return new HqSnapshot(operations, squads, productionLines, recent,
                state.AiCreatesObjectives, state.AiAutoFill);
        }

        /// <summary>Composition string from a unit-id→role map: "2× MBT, 1× IFV" (top 3 by count). Empty when
        /// no map is supplied (e.g. the enemy-side Hq) — the UI then falls back to the family ×strength form.</summary>
        private static string CompositionLabel(Squad s, IReadOnlyDictionary<string, Role> unitRoles)
        {
            if (unitRoles == null || s.MemberUnitIds == null || s.MemberUnitIds.Count == 0) return "";
            var counts = new Dictionary<string, int>();
            foreach (var id in s.MemberUnitIds)
            {
                if (!unitRoles.TryGetValue(id, out var role)) continue;
                var lbl = RoleLabels.Short(role);
                counts[lbl] = counts.TryGetValue(lbl, out var c) ? c + 1 : 1;
            }
            if (counts.Count == 0) return "";
            return string.Join(", ", counts
                .OrderByDescending(kv => kv.Value).ThenBy(kv => kv.Key)
                .Take(3)
                .Select(kv => $"{kv.Value}× {kv.Key}"));
        }

        /// <summary>What a squad is doing: its operation's objective + combat phase if engaged, else its
        /// status (Reserve/Forming/Ready). Manual squads are flagged as player-held.</summary>
        private static string SquadActivity(Squad s, CommanderState state)
        {
            if (s.Autonomy == AutonomyLevel.Manual) return "YOURS (manual)";
            if (!string.IsNullOrEmpty(s.AssignedOperationId))
            {
                var op = state.Operations.Find(o => o.Id == s.AssignedOperationId);
                if (op != null) return $"{op.Objective.Kind} — {op.CombatPhase}";
            }
            return s.Status.ToString();
        }
    }
}
