using System;
using System.IO;
using System.Linq;
using System.Text;
using Mono.Cecil;

// Code generator: mirrors selected enums from the REAL game assembly into a generated C# file so the mod
// keys off the game's single source of truth (DRY, type-safe). A contract test asserts the mirror matches
// the assembly, so a game update that changes an enum fails CI until this is regenerated.
//
// Run: dotnet run --project tools/CommanderLayer.CodeGen   (from the repo root; needs lib/Assembly-CSharp.dll)

// The enums we depend on (global namespace in Assembly-CSharp). Add to this list as the mod grows.
string[] enumsToMirror = { "VehicleType", "ShipType", "BuildingType", "FactionMode" };

string repoRoot = FindRepoRoot() ?? throw new Exception("Could not find repo root (looked for lib/Assembly-CSharp.dll upward).");
string dllPath = Path.Combine(repoRoot, "lib", "Assembly-CSharp.dll");
string outPath = Path.Combine(repoRoot, "src", "Core", "Generated", "GameEnums.generated.cs");

var resolver = new DefaultAssemblyResolver();
resolver.AddSearchDirectory(Path.Combine(repoRoot, "lib"));
using var asm = AssemblyDefinition.ReadAssembly(dllPath, new ReaderParameters { AssemblyResolver = resolver });
var module = asm.MainModule;

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     Generated by tools/CommanderLayer.CodeGen from the game's Assembly-CSharp.dll.");
sb.AppendLine("//     DO NOT EDIT. Regenerate via scripts/generate-types.sh. Drift is asserted by a contract test.");
sb.AppendLine($"//     Source enums: {string.Join(", ", enumsToMirror)}");
sb.AppendLine("// </auto-generated>");
sb.AppendLine("#pragma warning disable CS1591");
sb.AppendLine();
sb.AppendLine("namespace CommanderLayer.Core.Generated");
sb.AppendLine("{");

int emitted = 0;
foreach (var name in enumsToMirror)
{
    var t = module.GetType(name);
    if (t == null || !t.IsEnum)
    {
        Console.Error.WriteLine($"WARN: enum '{name}' not found or not an enum in Assembly-CSharp; skipping.");
        continue;
    }
    sb.AppendLine($"    /// <summary>Mirror of game enum <c>{name}</c> (auto-generated).</summary>");
    sb.AppendLine($"    public enum {name}");
    sb.AppendLine("    {");
    foreach (var f in t.Fields.Where(f => f.IsLiteral && f.Name != "value__"))
    {
        sb.AppendLine($"        {f.Name} = {Convert.ToInt64(f.Constant)},");
    }
    sb.AppendLine("    }");
    sb.AppendLine();
    emitted++;
}

sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"Generated {emitted} enum(s) -> {outPath}");
return 0;

static string? FindRepoRoot()
{
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir != null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "lib", "Assembly-CSharp.dll"))) return dir.FullName;
        dir = dir.Parent;
    }
    // fall back to walking up from the executable location
    dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir != null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "lib", "Assembly-CSharp.dll"))) return dir.FullName;
        dir = dir.Parent;
    }
    return null;
}
